export const YEAR_MONTH_REGEX = /^\d{4}-(0[1-9]|1[0-2])$/
export const PASSWORD_REGEX = /^(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#]).+$/
export const INNER_SPACES_REGEX = /^\S+$/
export const ORCID_NUMBER_VALIDATION_REGEX = /^(\d{4}-){3}\d{3}[\dX]$/
export const SQL_IDENTIFIER_REGEX = /^[a-zA-Z_][a-zA-Z0-9_]*$/
export const TOKEN_DURATION_REGEX = /^(?:[1-9]\d*(?:[ywdhms]))+$/i
export const RNE_VALIDATION_REGEX = /^[A-Za-z]\d{6}-\d$/
export const PASSPORT_VALIDATION_REGEX = /^[A-Z0-9]{6,9}$/
export const UPPERCASE_PASSWORD_CHARACTERS_REGEX = /[A-Z]/
export const LOWERCASE_PASSWORD_CHARACTERS_REGEX = /[a-z]/
export const PASSWORD_DIGIT_REGEX = /[0-9]/
export const PASSWORD_SPECIAL_CHARACTER_REGEX = /[\W_]/
