export const LIMITED_CHARACTERS_SIZE = 512
export const LONG_LIMITED_CHARACTERS_SIZE = 1000
export const VALID_DATE_RANGE_YEARS = 100
export const MAX_INTEREST_DESCRIPTION_SIZE = 2000
export const RANDOM_BYTES_NUMBER = 32
export const MIN_PASSWORD_SIZE = 8
export const MAX_PASSWORD_SIZE = 64
